; QS Force-sensitive gripper — ESP32 DevKit V1
; pio run -t upload
; pio device monitor

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
monitor_eol = LF
upload_speed = 115200
